# Site settings
title: Trophy
headline: 
email: thomas.vaeth@gmail.com
description: Trophy is a blog theme for Jekyll by Thomas Vaeth in Seattle, WA.
baseurl: ""
url: ""
twitter:
  username: thomasvaeth
paginate: 10
paginate_path: "/blog/page-:num"

# Build settings
include: ["_categories"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Default Settings

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-seo-tag, octopress-autoprefixer]
