# Site settings
email: "alfsaav@gmail.com"
baseurl: ""
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics: 

# SEO settings
title: Console 84
description: "A sexy developer microblog"
url: ""
twitter_username: 
default_img: 

# Profile settings
name: "Alfredo Saavedra"
profile_img: 
profile: "Just a dude that likes JavaScript and comp-scy"
social:
  github: 

# Build settings
exclude: ["_screenshots", "Gemfile", "Gemfile.lock", "LICENSE.txt", "README.md"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
