# Site settings
title: Pudding
email: thomas.vaeth@gmail.com
description: Pudding is a blog theme for Jekyll designed and developed by Thomas Vaeth.
baseurl: ""
url: ""
twitter:
  username: thomasvaeth
paginate: 10
paginate_path: "/blog/page-:num"

# Build settings
markdown: kramdown
permalink: pretty

# Default Settings

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-seo-tag, octopress-autoprefixer]
